definitions:
  viewModel.CreateLeaseRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  viewModel.EditLeaseRequest:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    type: object
  viewModel.Lease:
    properties:
      id:
        type: integer
      name:
        type: string
      ownerID:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Server for subleasing website ReLease
  title: ReLease API
  version: "1.0"
paths:
  /leases:
    get:
      description: get all leases
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/viewModel.Lease'
            type: array
        "500":
          description: Internal Server Error
      summary: List leases
      tags:
      - leases
    post:
      consumes:
      - application/json
      description: post a lease
      parameters:
      - description: create lease request
        in: body
        name: createLeaseRequest
        required: true
        schema:
          $ref: '#/definitions/viewModel.CreateLeaseRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: id of created lease
          schema:
            type: integer
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Auth0: []
      summary: Create a lease
      tags:
      - leases
  /leases/{id}:
    delete:
      description: delete a lease by id
      parameters:
      - description: lease id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Auth0: []
      summary: Delete a lease
      tags:
      - leases
    put:
      consumes:
      - application/json
      description: update a lease by id
      parameters:
      - description: lease id
        in: path
        name: id
        required: true
        type: integer
      - description: edit lease request
        in: body
        name: editLeaseRequest
        required: true
        schema:
          $ref: '#/definitions/viewModel.EditLeaseRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Auth0: []
      summary: Update a lease
      tags:
      - leases
securityDefinitions:
  Auth0:
    description: Auth0 protects our endpoints
    flow: application
    tokenUrl: https://dev-nkzmwy1mucvvl5xb.us.auth0.com/oauth/token
    type: oauth2
swagger: "2.0"
